language: ruby
rvm:
  - 1.9.3
env:
  global:
    secure: YqbzC160POPAZqhCDiE7rLKjhUfS39TPzinf4LwsfmsQFxJt9NAfDyoVqlixQwFDjBJLUUKEbRIrm7Hy2cxkUPMw2yY9nLC4+T6eO3UpIpJNEBzYGQ5WnS59q1ciO1t/7sRh4NXiu80qzjB/1P9K3BkIzv1ZdjVUvLTgNIFy7olh4r5d7S4mrWWssmpujuAWt3Wb4rujWcgPWp072R/1MWd9Sup8ZPofGW4ovjDNiHnnkpY1oOcW5RMLfg1VGZ9EQvKYqUBnOx5cR5br7rCsNi0zevGhmaWbSjuAermVPtpFlqFu/1wpUH+Aq2q5k3fC1cY28pAB7pTIMrc68dhZ41fcIz34UxNVDvjyVQt4tivxjYaoDYsmfAI3QKkri++E9PSYoikKb8QIZk3nfhZuN0kctJfhUwGA84fUYhCari1s50DuZPJMourCndmjBfbRN2M0YrIpm3ng+LXWCdgkCZAyV6a6T3ZnsNADkROlBJwRf6Y3EllaAtGDn3nAmxZfoGpBk8Ri3wAMRO2lFxuUERZS88swV0NlrsXPpbxvbh5cxy2PtQSsc9Mli8fJBFkXzq9udBuSn1cmhKFDfHKBYKwwkgWVuLmmVpao9LjOdsRk+BNAphbyHDv3ZPbng4fNVklixXw8ZPKkhZoVEFLBrirGrazCQDVnH9leZtBhnUs=
